import type { Metadata } from 'next';
import './globals.scss';
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/carousel/styles.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode // eslint-disable-line no-undef
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider
					theme={{
						fontFamily: 'IBM Plex Sans, sans-serif',
					}}
				>
					{children}
				</MantineProvider>
			</body>
		</html>
	);
}
